trigger:
  branches:
    include:
      - dev

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: "Release"
  solution: "**/WebApi.sln"
  project: "**/WebApi.csproj"
  tests: "**/WebApiTests.csproj"

steps:
  - task: NuGetToolInstaller@1
    displayName: "InstallNugetTool"

  - script: |
      echo Restoring NuGet packages...
      nuget restore $(solution)

      echo Running unit tests...
      dotnet test $(tests) --configuration $(buildConfiguration)

      echo Building and publishing artifact...
      dotnet publish $(project) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
      zip $(Build.ArtifactStagingDirectory)/*.dll
    displayName: "Run Tasks Sequentially"

  - task: PublishBuildArtifacts@1
    displayName: "PublishArtifact"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "webapiartifact"
      publishLocation: "Container"
