resources:
  repositories:
  - repository: WebApi
    type: git
    name: 'Training Web Api/WebApi'
  - repository: WebApi.Tests
    type: git
    name: 'Training Web Api/WebApi.Tests'

trigger:
  branches:
    include:
      - dev

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: 'Release'
  solution: '**/WebApi.sln'
  project: '**/WebApi.csproj'
  tests: '**/WebApi.Tests.csproj'

steps:
  - task: NuGetToolInstaller@1
    name: "InstallNugetTool"

  - task: NuGetCommand@2
    name: "RestoreNugetPackages"
    inputs:
      command: "restore"
      restoreSolution: "$(solution)"
      feedsToUse: "select"

  - task: NuGetCommand@2
    name: 'RestoreTestPackages'
    inputs:
      command: 'restore'
      restoreSolution: '$(testsSolution)'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    name: "RunUnitTest"
    inputs:
      command: "test"
      projects: "$(tests)"
      arguments: "--configuration $(buildConfiguration)"

  - task: DotNetCoreCLI@2
    name: "BuildArtifact"
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "$(project)"
      arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    name: "PublishArtifact"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "webapiartifact"
      publishLocation: "Container"
