resources:
  repositories:
  - repository: TrainingWebApiRepo
    type: git
    name: 'Training Web Api/TrainingWebApiRepo'
  - repository: TrainingWebApiTestsRepo
    type: git
    name: 'Training Web Api/TrainingWebApiTestsRepo'

trigger:
  branches:
    include:
      - dev

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: "Release"
  solution: "**/WebApi.sln"
  project: "**/WebApi.csproj"
  tests: "**/WebApiTests.csproj"

steps:
  - task: NuGetToolInstaller@1
    name: "InstallNugetTool"

  - task: NuGetCommand@2
    name: "RestoreNugetPackages"
    inputs:
      command: "restore"
      restoreSolution: "$(solution)"
      feedsToUse: "select"

  - task: DotNetCoreCLI@2
    name: "RunUnitTest"
    inputs:
      command: "test"
      projects: "$(tests)"
      arguments: "--configuration $(buildConfiguration)"

  - task: DotNetCoreCLI@2
    name: "BuildArtifact"
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "$(project)"
      arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    name: "PublishArtifact"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "webapiartifact"
      publishLocation: "Container"
